
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/tomas/Android/Sdk/cmake/4.0.2/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: Android - 1 - aarch64
      The host system is: Linux - 6.11.0-28-generic - x86_64
...
